codecov:
  token: 0b8da61e-b871-48d3-8549-f45203aeafb1

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 5%

ignore:
  - "src/main.rs"
  - "src/commands.rs"
  - "examples/**"
  - "tests/**"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

flags:
  unittests:
    paths:
      - "src/"
    carryforward: true
