<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NTIX.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LuaCSharp" Version="0.5.5" />
    <PackageReference Include="WGet.NET" Version="4.4.1" />
  </ItemGroup>

</Project>
