name: CI

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu
          components: llvm-tools-preview

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install Mingw-w64 linker
        run: choco install mingw -y

      - name: Build
        run: cargo build --all-targets --target x86_64-pc-windows-gnu

      - name: Test
        run: cargo test --target x86_64-pc-windows-gnu

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Test with coverage
        run: cargo llvm-cov --target x86_64-pc-windows-msvc --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
